unique_ids:
  assets:
    standard-page.html: KBQXY7JFMYB5T4EKM5TILGWYULKM3UKC
    theme.css: SP3W7TVFGC5A7QFYPY7OSXVYDO4B2A63
  forms:
    Form1: VITMDO44P4V654GYRNLZ6LBZPWW5UGL2
  modules: {}
  scripts: {}
  server_modules: {}
